### PR TITLE
update new files

### PR DESCRIPTION
**Pull request by LinguList**
Please check this carefully. It adds the wordlist now as wordlist data, while we still add the dictionary, and we share the IDs for the entries.

See metadata.json also and provide a full reference. See also how I include your concept list.

What is missing is a more rigorous refinement of the wordlist, by dropping cases of excess synonymy. In my opinion, there should be maximally two words per concept, not five as in many cases. One should avoid having too many half-matches, but conform to the concepticon concept as closely as possible, and rather leave it empty otherwise.

### CODE REVIEW

**Comment by martino-vic** [comment]
Thank you very much for taking care of this. One thing I realised but don't manage to fix myself is that the "Part_of_Speech" column in entries.csv is not being filled. If I print out `row["pos"]` in the loop, the strings are shown correctly, but somehow in [line 115](https://github.com/martino-vic/streitberggothic/blob/new/lexibank_streitberggothic.py#L115) nothing gets plugged in. If I change  `row["pos"]` to a regular string like `"test"`, also nothing gets plugged in. I don't really understand this behaviour, so I was wondering if you maybe know what is causing this.

**Comment by martino-vic** [comment]
Ah, solved it. The problem was the good old camel-snake: The column is called "Part_Of_Speech", not "Part_of_Speech"

**Comment by martino-vic** [comment]
Refined wordlist.tsv once more, so that no concept occurs more than twice, added a full citation. Pushed the new repository.

**Comment by LinguList** [comment]
Nice, please wait with a release this time. I'd say a proper release should not be accompanied by some improvement of the synonyms in the concept list.

**Comment by LinguList** [comment]
I will also contact our collaborators on Monday, so they help me reviewing this kind of integration across two CLDF datasts, which is the first example of this kind.

**Comment by martino-vic** [comment]
Just tried to run it on the gerstnerhungarian data set and it seems there's a circular argument involved: To create wordlist.tsv with the new cldfbench command we need Dictionary-metadata.json, but to create Dictionary-metadata.json we need to to run the lexibank_*-script, which needs wordlist.tsv

**Comment by martino-vic** [comment]
I mean I could make a hacky work around but I guess the goal was to have one script that just runs and does the job

**Comment by martino-vic** [comment]
I've use a try-except clause as a workaround: If wordlist.tsv is missing, the block where it's needed is skipped. Afterwards, one can create wordlist.tsv and after that rerun the lexibank_*-script. A bit hacky, but works.

**Comment by martino-vic** [comment]
I've used a try-except clause as a workaround: If wordlist.tsv is missing, the block where it's needed is skipped. Afterwards, one can create wordlist.tsv and after that rerun the lexibank_*-script. A bit hacky, but works.

**Comment by martino-vic** [comment]
I've used a try-except clause as a workaround: If wordlist.tsv is missing, the block where it's needed is skipped. Afterwards, one can create wordlist.tsv and after that rerun the lexibank_*-script. A bit hacky, but works.

**Comment by LinguList** [comment]
Yes, I knew that the procedure is somewhat circular, with the lexibank script. Or iterative. The problem is the assignment of languages. But note that we often encounter some of these problems with concrete data, and that the integration of one part of the data requires to have integrated the other part. E.g., we write a download command first, then we write a parse data command, and then we extract concepts and then we add them to concepticon and have to change the code again. 

So I think that the important aspect is the final product, and the open workflow for the refinement of the wordlist (you modify, you run the script again) or the dictionary file (you find errors, you compute it), so I'd say that I gladly accept the circularity problem, involving some uncommenting of code when getting started, specifically in this stage where we still have not settled on the whole workflow.

**Comment by LinguList** [comment]
One other possibility that is also a bit hacky would be to use the download command in lexibank to not only download the data, but to prepare only the dictionary part and to run the wordlist creation routine. The combined creation of CLDF data would then be done in the makecldf command.

**Comment by LinguList** [comment]
But to summarize the workflow for now:

1. create the dictionary in regular CLDF data, accounting for a rigorous distinction of senses, which can be assigned to the same entry (one entry has a meaning, consisting of multiple senses, individual for that word [the individual for that word part is required by dictionaria, but I am not in favor of it, but well, we start from what we have])
2. use our extraction script to extract a wordlist mapping to the individual senses for a wordlist W and write it with forms to file, so that it can be modified by the data curator, deleting multiple synonyms, etc.
3. modify the wordlist
4. make the full lexibank script creating a wordlist and a dictionary in which entry_id and sense_id from the dictionary is shared across both datasets
5. refine the lexibank script by providing an orthography profile for the wordlist data (here, note that you could do this for the dictionary as well, but for now, we only do it for the wordlist, which I consider sufficient for now)

I think that this workflow, if applied to some more languages, can be submitted as a study to some targeted journal (small database/data curation article). We could exchange about this via email.

**Pull request merged**
