### PR TITLE
Main

### PR DESCRIPTION
**Pull request by LinguList**
@martino-vic, please check with the new code, also the lexibank_*.script, which I refined a bit. The first part is only there, so that all is written correctly (the lexibank wordlist writing routine). The new part splits sense descriptions as this seems more consistent. The concept mapping and writing to a wordlist in `raw` is now done with a specific command:

```
$ cldfbench streitberggothic.map
```

This does the trick, it accepts arguments (for outsourcing it later), like `--language`, `--format` (default="simple", you can also do "pipe", "html", etc.) and the conceptlist (default the NorthEuralex list).

### CODE REVIEW

**Comment by LinguList** [comment]
The wordlist has ~ 1200 forms, which is not that much, so duplicates are not soo many there. I recommend to really check this thoroughly and delete those which don't fit. As a result, one has a nice Gothic wordlist.

**Comment by martino-vic** [comment]
The lexibank_*-script works fine, but if I'm running `cldfbench streitberggothic.map` I'm getting `cldfbench: error: argument COMMAND: invalid choice: 'streitberggothic.map'`

**Comment by martino-vic** [comment]
Ah, I moved the new map.py file into my virtual environment to site-packages/cldfbench/commands and now `$ cldfbench map` worked nicely :)

**Comment by LinguList** [comment]
Don't do this. Just run `pip install -e .` inside the directory and leave the file in the commands folder.

**Comment by LinguList** [comment]
This is how we provide specific code pieces when working with individual repositories.

**Comment by martino-vic** [comment]
Ah okay, yes that works too now, thanks. I had tried this before but just realised I had typed `-e.` instead of 
`-e .` that's why it failed

**Comment by martino-vic** [comment]
I'm just manually checking [wordlist.tsv](https://github.com/martino-vic/streitberggothic/blob/new/raw/wordlist.tsv) and:

- diacritics somehow disappeared in column "senses: e.g. ["Korper" instead of "Körper"](https://github.com/martino-vic/streitberggothic/blob/new/raw/wordlist.tsv#L104)
- some concepts that pysem earlier identified are empty now: e.g. [SUDDENLY missing in wordlist.tsv](https://github.com/martino-vic/streitberggothic/blob/new/raw/wordlist.tsv#L998) vs. [SUDDENLY present in concepts2.tsv](https://github.com/martino-vic/streitberggothic/blob/new/etc/concepts2.tsv#L25)

**Comment by LinguList** [comment]
The missing diacritics point to a confusion of the entries and the ID.

**Comment by LinguList** [comment]
Here's the line that causes these problems: 

https://github.com/martino-vic/streitberggothic/blob/8b428c211ac37fcbbae315e196575db26bf6cf93/lexibank_streitberggothic.py#L103

What happens is that I slug (remove diacritics, etc.) the sense to have a sense ID, but then treat this as the sense headword.

**Comment by LinguList** [comment]
Easy to modify:

```python
            senses[slug(sense.strip(), lowercase=False)] += [(fidx, sense)]
            for sense, values in senses.items():
                for i, (fidx, sense_desc) in enumerate(values):
                    writer.objects["SenseTable"].append({
                        "ID": sense+"-"+str(i+1),
                        "Description": sense_desc,
                        "Entry_ID": fidx
                        })

**Comment by martino-vic** [comment]
Ah, yes, works perfectly! Am continuing the manual check, am going to push the new version soon

**Comment by martino-vic** [comment]
just figured out the solution for the other issue as well: senses were only split on "," in [line 101](https://github.com/martino-vic/streitberggothic/blob/new/lexibank_streitberggothic.py#L101), so I replaced `row["sense"].split(",")` with `re.split([",;"], row["sense"])`, now words like "plötzlich" get their own row and are correctly identified as concepts as well 👍

**Comment by martino-vic** [comment]
So I have manually refined [wordlist.tsv](https://github.com/martino-vic/streitberggothic/blob/new/raw/wordlist.tsv) now but I'm not entirely sure what the next step would be, so I thought I'd better ask here first. I guess the info from worldist.tsv should be somehow included in concepts.tsv, so that columns Concepticon_ID and Concepticon_Gloss in parameters.csv can be reactivated?

**Comment by LinguList** [comment]
Let me do the next step, easier to do it in code than to explain it.

**Pull request merged**
